/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/diamond.gltf');
	return (
		<group ref={group} {...props} dispose={null}>
			<group
				position={[1, 2, 0]}
				autoRotate
				rotation-y={2}
				rotation={props.clicked ? [0, -1.29, 0.13] : [-Math.PI, -1.29, 0.13]}
			>
				<mesh
					geometry={nodes.Cone_1.geometry}
					material={materials['SVGMat.001']}
				/>
				<mesh
					geometry={nodes.Cone_2.geometry}
					material={materials['SVGMat.002']}
				/>
				<mesh
					geometry={nodes.Cone_3.geometry}
					material={materials['SVGMat.003']}
				/>
				<mesh
					geometry={nodes.Cone_4.geometry}
					material={materials['SVGMat.004']}
				/>
				<mesh
					geometry={nodes.Cone_5.geometry}
					material={materials['SVGMat.005']}
				/>
				<mesh
					geometry={nodes.Cone_6.geometry}
					material={materials['SVGMat.006']}
				/>
				<mesh
					geometry={nodes.Cone_7.geometry}
					material={materials['SVGMat.007']}
				/>
				<mesh
					geometry={nodes.Cone_8.geometry}
					material={materials['SVGMat.008']}
				/>
				<mesh
					geometry={nodes.Cone_9.geometry}
					material={materials['SVGMat.009']}
				/>
				<mesh
					geometry={nodes.Cone_10.geometry}
					material={materials['SVGMat.010']}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/diamond.gltf');
