/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import type { GroupProps } from '@react-three/fiber';
import type { BufferGeometry, Group, Material, Mesh } from 'three';
import { publicAsset } from '../utils/publicAsset';

const modelUrl = publicAsset('diamond.gltf');

type ConeName = `Cone_${1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10}`;
type MaterialName = `SVGMat.${
	| '001'
	| '002'
	| '003'
	| '004'
	| '005'
	| '006'
	| '007'
	| '008'
	| '009'
	| '010'}`;

type DiamondMesh = Mesh<BufferGeometry, Material>;
type DiamondGLTF = ReturnType<typeof useGLTF> & {
	nodes: Record<ConeName, DiamondMesh>;
	materials: Record<MaterialName, Material>;
};

interface ModelProps extends GroupProps {
	clicked: boolean;
}

export default function Model({ clicked, ...props }: ModelProps) {
	const group = useRef<Group>(null);
	const { nodes, materials } = useGLTF(modelUrl) as DiamondGLTF;
	return (
		<group ref={group} {...props} dispose={null}>
			<group
				position={[1, 2, 0]}
				rotation={clicked ? [0, -1.29, 0.13] : [-Math.PI, -1.29, 0.13]}
			>
				<mesh
					geometry={nodes.Cone_1.geometry}
					material={materials['SVGMat.001']}
				/>
				<mesh
					geometry={nodes.Cone_2.geometry}
					material={materials['SVGMat.002']}
				/>
				<mesh
					geometry={nodes.Cone_3.geometry}
					material={materials['SVGMat.003']}
				/>
				<mesh
					geometry={nodes.Cone_4.geometry}
					material={materials['SVGMat.004']}
				/>
				<mesh
					geometry={nodes.Cone_5.geometry}
					material={materials['SVGMat.005']}
				/>
				<mesh
					geometry={nodes.Cone_6.geometry}
					material={materials['SVGMat.006']}
				/>
				<mesh
					geometry={nodes.Cone_7.geometry}
					material={materials['SVGMat.007']}
				/>
				<mesh
					geometry={nodes.Cone_8.geometry}
					material={materials['SVGMat.008']}
				/>
				<mesh
					geometry={nodes.Cone_9.geometry}
					material={materials['SVGMat.009']}
				/>
				<mesh
					geometry={nodes.Cone_10.geometry}
					material={materials['SVGMat.010']}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(modelUrl);
